//
//  TodoListPresenter.h
//  CleanArchitectureForObjective-C
//
//  Created by Naoki_Sawada on 2017/02/21.
//  Copyright (c) 2017年 CAFObjC. All rights reserved.
//
//  This file was generated by the Clean ObjectiveC Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, base on http://clean-swift.com

@import Foundation;

@class TodoListViewModel;
@class TodoListResponse;

@protocol TodoListPresenterOutput <NSObject>
@required
- (void)displaySomething:(TodoListViewModel *)viewModel;
@end

@protocol TodoListPresenterInput <NSObject>
@required
- (void)presentSomething:(TodoListResponse *)response;
@end


@interface TodoListPresenter : NSObject <TodoListPresenterInput>

@property (nonatomic, weak) id<TodoListPresenterOutput> output;
@end
