//
//  TodoListViewController.h
//  CleanArchitectureForObjective-C
//
//  Created by Naoki_Sawada on 2017/02/21.
//  Copyright (c) 2017年 CAFObjC. All rights reserved.
//
//  This file was generated by the Clean ObjectiveC Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, base on http://clean-swift.com

@import UIKit;

@class TodoListRouter;
@class TodoListRequest;
@class TodoListViewModel;

@protocol TodoListViewControllerOutput <NSObject>
@required
- (void)fetchTodoItems:(TodoListRequest *)request;
@end


@protocol TodoListViewControllerInput <NSObject>
@required
- (void)displaySomething:(TodoListViewModel *)viewModel;
@end



@interface TodoListViewController : UITableViewController <TodoListViewControllerInput>

+ (instancetype)selfViewController;

@property (nonatomic) TodoListRouter *router;
@property (nonatomic) id<TodoListViewControllerOutput> output;
@property (nonatomic) NSManagedObjectContext *managedObjectContext;

@end

@interface TodoListViewController (Storyboard)
+ (instancetype)selfViewControllerWithStoryboardName:(NSString *)storyboardName;
@end
